baseurl = "https://example.com/"
# remember trailing / at end of baseurl
languageCode = "en-us"
title = "SublimeR Hugo"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50
theme = "sublime-hugo-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Homer White"
	description = "Tweak of Sublime Hugo theme for blogdown"
	copyright = "License:  MIT"
	sharing = true
	showsummaries = true
	
	# store off-canvas log image in static/img:
	logo = "offcanvas-shot.jpg"
	logoborderradius = "10%"
	
	# enable MathJax on all pages by default?
	math = false

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hello, I'm Homer White"
	bio = "I teach mathematics and computer science at a small liberal arts college in Kentucky.  In the summer I hack at garden hedges and front ends."
	bio2 = ""
	subscribe = "Subscribe"
	followme = "Contact/Follow"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Email"
		url = "mailto:homerhanumat@gmail.com"
		github = "homerhanumat"
		facebook = ""
		twitter = ""
		# for Google Plus, provide URL fragment after the +:
		googleplus = ""
		linkedin = ""
		
# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  aggregator = "aggregators"
